mysql:
  image: mysql
  command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  volumes:
    - "./mysql/init:/docker-entrypoint-initdb.d"
  ports:
    - "3307:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=password
